# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  download_theme:
    aliases: [dt]
    desc: Download the theme from the source repository
    cmds:
      - rm -rf themes/simpleness
      - git clone https://github.com/RainerChiang/simpleness.git themes/simpleness

  hugo:
    desc: Build the Hugo site
    cmds:
      - hugo --minify

  serve:
    desc: Run Hugo development server
    cmds:
      - hugo server -D

  server:
    desc: Build and run the Go file server locally against public/
    deps: [hugo]
    cmds:
      - go run ./cmd/server -dir public

  container-build:
    desc: Build the container image with Podman
    cmds:
      - podman build -t blog:local -f Containerfile .

  container-run:
    desc: Run the container image locally
    deps: [container-build]
    cmds:
      - podman run --rm -p 8080:8080 blog:local

  infra-init:
    desc: Initialize Terraform/OpenTofu
    dir: infra
    cmds:
      - tofu init

  infra-plan:
    desc: Show Terraform/OpenTofu plan
    dir: infra
    cmds:
      - tofu plan

  infra-apply:
    desc: Apply Terraform/OpenTofu changes
    dir: infra
    cmds:
      - tofu apply

  check:
    desc: Run Go checks (fmt, vet, test)
    cmds:
      - go fmt ./...
      - go vet ./...

  release:*:*:
    desc: "Release: task release:v0.1.0:\"new blog post\""
    vars:
      TAG: '{{index .MATCH 0}}'
      MSG: '{{index .MATCH 1}}'
    cmds:
      - task: hugo
      - task: check
      - git add .
      - git commit -am "{{.MSG}}"
      - git tag "{{.TAG}}"
      - git push origin "{{.TAG}}"
      - git push

  book:md:
    desc: Generate combined AFP markdown (for debugging)
    cmds:
      - go run ./cmd/afp2book > afp-book.md
      - echo "Wrote afp-book.md"

  book:pdf:
    desc: Generate AFP book PDF via pandoc+typst
    cmds:
      - go run ./cmd/afp2book -pdf afp-book.pdf

